# Generated by Django 5.2 on 2025-04-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelTable(
            name='libro',
            table='biblioteca_libro',
        ),
        migrations.AlterModelTable(
            name='resena',
            table='biblioteca_resena',
        ),
    ]
