# Generated by Django 5.2 on 2025-04-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_libro_options_alter_resena_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelTable(
            name='autor',
            table=None,
        ),
    ]
