# Generated by Django 5.2 on 2025-04-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_autor_options_alter_autor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelTable(
            name='autor',
            table='biblioteca_autor',
        ),
    ]
