# Generated by Django 5.2 on 2025-04-21 17:55

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_autor_options_alter_autor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_nombre_no_vacio]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(validators=[biblioteca.models.validar_resumen_minimo]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(validators=[biblioteca.models.validar_calificacion]),
        ),
    ]
