# Generated by Django 5.2 on 2025-05-08 01:51

import biblioteca.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_resena_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.FloatField(validators=[biblioteca.models.validar_calificacion, django.core.validators.MinValueValidator(0.0, message='La calificación no puede ser menor a 0.0'), django.core.validators.MaxValueValidator(5.0, message='La calificación no puede ser mayor a 5.0')]),
        ),
    ]
